using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Probora.Infrastructure.Persistence;

#nullable disable

namespace Probora.Infrastructure.Migrations;

[DbContext(typeof(ProboraDbContext))]
[Migration("20260714130000_AddDerivativeShadowSnapshots")]
public sealed class AddDerivativeShadowSnapshots : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE probora.derivative_daily_snapshots (
              "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              "AssetId" uuid NOT NULL REFERENCES probora.assets ("Id") ON DELETE CASCADE,
              "SnapshotTime" timestamptz NOT NULL,
              "FundingRate" double precision NOT NULL,
              "Premium" double precision NOT NULL,
              "FuturesQuoteVolume" double precision NOT NULL,
              "FuturesTakerBuyRatio" double precision NOT NULL,
              "OpenInterestValue" double precision NOT NULL,
              "LongShortRatio" double precision NOT NULL,
              "TakerLongShortRatio" double precision NOT NULL,
              "FuturesKlineCount" integer NOT NULL,
              "PremiumKlineCount" integer NOT NULL,
              "FundingPointCount" integer NOT NULL,
              "OpenInterestPointCount" integer NOT NULL,
              "LongShortPointCount" integer NOT NULL,
              "TakerLongShortPointCount" integer NOT NULL,
              "IsComplete" boolean NOT NULL,
              "SourceMaxEventTime" timestamptz NOT NULL,
              "AvailableAt" timestamptz NOT NULL,
              "IngestedAt" timestamptz NOT NULL,
              "Source" varchar(32) NOT NULL,
              "SourceChecksum" varchar(64) NOT NULL
            );
            CREATE UNIQUE INDEX "IX_derivative_snapshots_identity"
              ON probora.derivative_daily_snapshots ("AssetId", "SnapshotTime", "Source");
            CREATE INDEX "IX_derivative_snapshots_readiness"
              ON probora.derivative_daily_snapshots ("AssetId", "IsComplete", "SnapshotTime");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DROP TABLE IF EXISTS probora.derivative_daily_snapshots;");
}
