using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Probora.Infrastructure.Persistence;

#nullable disable

namespace Probora.Infrastructure.Migrations;

[DbContext(typeof(ProboraDbContext))]
[Migration("20260713120000_InitialCreate")]
public sealed class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE SCHEMA IF NOT EXISTS probora;

            CREATE TABLE probora.assets (
              "Id" uuid PRIMARY KEY,
              "Symbol" varchar(20) NOT NULL,
              "BaseAsset" varchar(20) NOT NULL,
              "QuoteAsset" varchar(20) NOT NULL,
              "DisplayName" text NOT NULL,
              "DataStartsAt" timestamptz NOT NULL,
              "IsActive" boolean NOT NULL
            );
            CREATE UNIQUE INDEX "IX_assets_Symbol" ON probora.assets ("Symbol");
            INSERT INTO probora.assets
              ("Id", "Symbol", "BaseAsset", "QuoteAsset", "DisplayName", "DataStartsAt", "IsActive")
            VALUES
              ('00000000-0000-0000-0000-000000000001', 'BTCUSDT', 'BTC', 'USDT', 'Bitcoin', '2017-08-01T00:00:00Z', true),
              ('00000000-0000-0000-0000-000000000002', 'ETHUSDT', 'ETH', 'USDT', 'Ethereum', '2017-08-01T00:00:00Z', true),
              ('00000000-0000-0000-0000-000000000003', 'SOLUSDT', 'SOL', 'USDT', 'Solana', '2020-08-01T00:00:00Z', true),
              ('00000000-0000-0000-0000-000000000004', 'BNBUSDT', 'BNB', 'USDT', 'BNB', '2017-11-01T00:00:00Z', true),
              ('00000000-0000-0000-0000-000000000005', 'XRPUSDT', 'XRP', 'USDT', 'XRP', '2018-05-01T00:00:00Z', true),
              ('00000000-0000-0000-0000-000000000006', 'ADAUSDT', 'ADA', 'USDT', 'Cardano', '2018-04-01T00:00:00Z', true),
              ('00000000-0000-0000-0000-000000000007', 'LINKUSDT', 'LINK', 'USDT', 'Chainlink', '2019-01-01T00:00:00Z', true),
              ('00000000-0000-0000-0000-000000000008', 'DOGEUSDT', 'DOGE', 'USDT', 'Dogecoin', '2019-07-01T00:00:00Z', true);

            CREATE TABLE probora.price_bars (
              "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              "AssetId" uuid NOT NULL REFERENCES probora.assets ("Id") ON DELETE CASCADE,
              "OpenTime" timestamptz NOT NULL,
              "CloseTime" timestamptz NOT NULL,
              "Interval" varchar(8) NOT NULL,
              "Open" numeric(28,10) NOT NULL,
              "High" numeric(28,10) NOT NULL,
              "Low" numeric(28,10) NOT NULL,
              "Close" numeric(28,10) NOT NULL,
              "Volume" numeric(36,12) NOT NULL,
              "QuoteVolume" numeric(36,12) NOT NULL,
              "TradeCount" bigint NOT NULL,
              "TakerBuyBaseVolume" numeric(36,12) NOT NULL,
              "TakerBuyQuoteVolume" numeric(36,12) NOT NULL,
              "Source" varchar(32) NOT NULL,
              "IsFinal" boolean NOT NULL,
              "AvailableAt" timestamptz NOT NULL,
              "IngestedAt" timestamptz NOT NULL,
              "SourceChecksum" varchar(64) NULL
            );
            CREATE UNIQUE INDEX "IX_price_bars_identity" ON probora.price_bars ("AssetId", "OpenTime", "Interval", "Source");
            CREATE INDEX "IX_price_bars_lookup" ON probora.price_bars ("AssetId", "Interval", "OpenTime");

            CREATE TABLE probora.feature_snapshots (
              "Id" uuid PRIMARY KEY,
              "AssetId" uuid NOT NULL REFERENCES probora.assets ("Id") ON DELETE CASCADE,
              "SnapshotTime" timestamptz NOT NULL,
              "FeatureSetVersion" text NOT NULL,
              "FeaturesJson" jsonb NOT NULL,
              "InputDataSha256" text NOT NULL,
              "CreatedAt" timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX "IX_feature_snapshots_identity" ON probora.feature_snapshots ("AssetId", "SnapshotTime", "FeatureSetVersion");

            CREATE TABLE probora.model_versions (
              "Id" uuid PRIMARY KEY,
              "Version" text NOT NULL,
              "HorizonDays" integer NOT NULL,
              "FeatureSetVersion" text NOT NULL,
              "DatasetVersion" text NOT NULL,
              "ArtifactPath" text NOT NULL,
              "ArtifactSha256" text NOT NULL,
              "MetricsJson" jsonb NOT NULL,
              "TrainedAt" timestamptz NOT NULL,
              "IsProduction" boolean NOT NULL
            );
            CREATE UNIQUE INDEX "IX_model_versions_Version" ON probora.model_versions ("Version");
            CREATE INDEX "IX_model_versions_production" ON probora.model_versions ("HorizonDays", "IsProduction");

            CREATE TABLE probora.predictions (
              "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              "AssetId" uuid NOT NULL REFERENCES probora.assets ("Id") ON DELETE CASCADE,
              "ModelVersionId" uuid NOT NULL REFERENCES probora.model_versions ("Id") ON DELETE RESTRICT,
              "FeatureSnapshotId" uuid NOT NULL REFERENCES probora.feature_snapshots ("Id") ON DELETE RESTRICT,
              "AnalysisTime" timestamptz NOT NULL,
              "HorizonDays" integer NOT NULL,
              "UpProbability" double precision NOT NULL,
              "NeutralProbability" double precision NOT NULL,
              "DownProbability" double precision NOT NULL,
              "ReturnP10" double precision NOT NULL,
              "ReturnP50" double precision NOT NULL,
              "ReturnP90" double precision NOT NULL,
              "RiskScore" double precision NOT NULL,
              "RiskLevel" integer NOT NULL,
              "ConfidenceScore" double precision NOT NULL,
              "Status" integer NOT NULL,
              "PositiveFactorsJson" jsonb NOT NULL,
              "NegativeFactorsJson" jsonb NOT NULL,
              "LimitationsJson" jsonb NOT NULL,
              "ArtifactSha256" text NOT NULL,
              "CreatedAt" timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX "IX_predictions_identity" ON probora.predictions ("AssetId", "HorizonDays", "AnalysisTime");

            CREATE TABLE probora.ingestion_runs (
              "Id" uuid PRIMARY KEY,
              "Source" text NOT NULL,
              "Dataset" text NOT NULL,
              "StartedAt" timestamptz NOT NULL,
              "CompletedAt" timestamptz NULL,
              "Status" text NOT NULL,
              "RecordsRead" bigint NOT NULL,
              "RecordsWritten" bigint NOT NULL,
              "Error" text NULL
            );
            CREATE INDEX "IX_ingestion_runs_lookup" ON probora.ingestion_runs ("Source", "Dataset", "StartedAt");

            CREATE TABLE probora.data_quality_issues (
              "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              "AssetId" uuid NULL REFERENCES probora.assets ("Id") ON DELETE SET NULL,
              "Code" text NOT NULL,
              "Severity" text NOT NULL,
              "Description" text NOT NULL,
              "DataTime" timestamptz NULL,
              "DetectedAt" timestamptz NOT NULL,
              "IsResolved" boolean NOT NULL
            );
            CREATE INDEX "IX_data_quality_issues_lookup" ON probora.data_quality_issues ("AssetId", "DetectedAt");

            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DROP SCHEMA IF EXISTS probora CASCADE;");
}
